package com.application.apa.Enum;

public enum PaymentMethod {
	CASH, CHEQUE, BANK_TRANSFER, NEFT, RTGS, IMPS, UPI, CREDIT_CARD, DEBIT_CARD, NET_BANKING, PAYTM, GOOGLE_PAY,
	PHONE_PE, PAYPAL,DEMAND_DRAFT, PURCHASE_ORDER
}
